package com.r2development.leveris.utils.enums;

/**
 * Created by anthonymottot on 31/03/2016.
 */
public enum COUNTY_ENGLAND {

    BUCKINGHAMSHIRE ( "BKM" ),
    CAMBRIDGESHIRE ( "CAM" ),
    CUMBRIA ( "CMA" ),
    DERBYSHIRE ( "DBY" ),
    DEVON ( "DEV" ),
    DORSET ( "DOR" ),
    EAST_SUSSEX ( "ESX" ),
    ESSEX ( "ESS" ),
    GLOUCESTERSHIRE ( "GLS" ),
    HAMPSHIRE ( "HAM" ),
    HERTFORDSHIRE ( "HRT" ),
    KENT ( "KEN" ),
    LANCASHIRE ( "LAN" ),
    LEICESTERSHIRE ( "LEC" ),
    LINCOLNSHIRE ( "LIN" ),
    NORFOLK ( "NFK" ),
    NORTH_YORKSHIRE ( "NYK" ),
    NORTHAMPTONSHIRE ( "NTH" ),
    NOTTINGHAMSHIRE ( "NTT" ),
    OXFORDSHIRE ( "OXF" ),
    SOMERSET ( "SOM" ),
    STAFFORDSHIRE ( "STS" ),
    SUFFOLK ( "SFK" ),
    SURREY ( "SRY" ),
    WARWICKSHIRE ( "WAR" ),
    WEST_SUSSEX ( "WSX" ),
    WORCESTERSHIRE ( "WOR" ),
    LONDON_CITY_OF ( "LND" ),
    BARKING_AND_DAGENHAM ( "BDG" ),
    BARNET ( "BNE" ),
    BEXLEY ( "BEX" ),
    BRENT ( "BEN" ),
    BROMLEY ( "BRY" ),
    CAMDEN ( "CMD" ),
    CROYDON ( "CRY" ),
    EALING ( "EAL" ),
    ENFIELD ( "ENF" ),
    GREENWICH ( "GRE" ),
    HACKNEY ( "HCK" ),
    HAMMERSMITH_AND_FULHAM ( "HMF" ),
    HARINGEY ( "HRY" ),
    HARROW ( "HRW" ),
    HAVERING ( "HAV" ),
    HILLINGDON ( "HIL" ),
    HOUNSLOW ( "HNS" ),
    ISLINGTON ( "ISL" ),
    KENSINGTON_AND_CHELSEA ( "KEC" ),
    KINGSTON_UPON_THAMES ( "KTT" ),
    LAMBETH ( "LBH" ),
    LEWISHAM ( "LEW" ),
    MERTON ( "MRT" ),
    NEWHAM ( "NWM" ),
    REDBRIDGE ( "RDB" ),
    RICHMOND_UPON_THAMES ( "RIC" ),
    SOUTHWARK ( "SWK" ),
    SUTTON ( "STN" ),
    TOWER_HAMLETS ( "TWH" ),
    WALTHAM_FOREST ( "WFT" ),
    WANDSWORTH ( "WND" ),
    WESTMINSTER ( "WSM" ),
    BARNSLEY ( "BNS" ),
    BIRMINGHAM ( "BIR" ),
    BOLTON ( "BOL" ),
    BRADFORD ( "BRD" ),
    BURY ( "BUR" ),
    CALDERDALE ( "CLD" ),
    COVENTRY ( "COV" ),
    DONCASTER ( "DNC" ),
    DUDLEY ( "DUD" ),
    GATESHEAD ( "GAT" ),
    KIRKLEES ( "KIR" ),
    KNOWSLEY ( "KWL" ),
    LEEDS ( "LDS" ),
    LIVERPOOL ( "LIV" ),
    MANCHESTER ( "MAN" ),
    NEWCASTLE_UPON_TYNE ( "NET" ),
    NORTH_TYNESIDE ( "NTY" ),
    OLDHAM ( "OLD" ),
    ROCHDALE ( "RCH" ),
    ROTHERHAM ( "ROT" ),
    ST_HELENS ( "SHN" ),
    SALFORD ( "SLF" ),
    SANDWELL ( "SAW" ),
    SEFTON ( "SFT" ),
    SHEFFIELD ( "SHF" ),
    SOLIHULL ( "SOL" ),
    SOUTH_TYNESIDE ( "STY" ),
    STOCKPORT ( "SKP" ),
    SUNDERLAND ( "SND" ),
    TAMESIDE ( "TAM" ),
    TRAFFORD ( "TRF" ),
    WAKEFIELD ( "WKF" ),
    WALSALL ( "WLL" ),
    WIGAN ( "WGN" ),
    WIRRAL ( "WRL" ),
    WOLVERHAMPTON ( "WLV" ),
    BATH_AND_NORTH_EAST_SOMERSET ( "BAS" ),
    BEDFORD ( "BDF" ),
    BLACKBURN_WITH_DARWEN ( "BBD" ),
    BLACKPOOL ( "BPL" ),
    BOURNEMOUTH ( "BMH" ),
    BRACKNELL_FOREST ( "BRC" ),
    BRIGHTON_AND_HOVE ( "BNH" ),
    BRISTO_CITY_OF ( "BST" ),
    CENTRAL_BEDFORDSHIRE ( "CBF" ),
    CHESHIRE_EAST ( "CHE" ),
    CHESHIRE_WEST_AND_CHESTER ( "CHW" ),
    CORNWALL ( "CON" ),
    DARLINGTON ( "DAL" ),
    DERBY ( "DER" ),
    DURHAM_COUNTY ( "DUR" ),
    EAST_RIDING_OF_YORKSHIRE ( "ERY" ),
    HALTON ( "HAL" ),
    HARTLEPOOL ( "HPL" ),
    HEREFORDSHIRE ( "HEF" ),
    ISLE_OF_WIGHT ( "IOW" ),
    ISLES_OF_SCILLY ( "IOS" ),
    KINGSTON_UPON_HULL ( "KHL" ),
    LEICESTER ( "LCE" ),
    LUTON ( "LUT" ),
    MEDWAY ( "MDW" ),
    MIDDLESBROUGH ( "MDB" ),
    MILTON_KEYNES ( "MIK" ),
    NORTH_EAST_LINCOLNSHIRE ( "NEL" ),
    NORTH_LINCOLNSHIRE ( "NLN" ),
    NORTH_SOMERSET ( "NSM" ),
    NORTHUMBERLAND ( "NBL" ),
    NOTTINGHAM ( "NGM" ),
    PETERBOROUGH ( "PTE" ),
    PLYMOUTH ( "PLY" ),
    POOLE ( "POL" ),
    PORTSMOUTH ( "POR" ),
    READING ( "RDG" ),
    REDCAR_AND_CLEVELAND ( "RCC" ),
    RUTLAND ( "RUT" ),
    SHROPSHIRE ( "SHR" ),
    SLOUGH ( "SLG" ),
    SOUTH_GLOUCESTERSHIRE ( "SGC" ),
    SOUTHAMPTON ( "STH" ),
    SOUTHEND_ON_SEA ( "SOS" ),
    STOCKTON_ON_TEES ( "STT" ),
    STOKE_ON_TRENT ( "STE" ),
    SWINDON ( "SWD" ),
    TELFORD_AND_WREKIN ( "TFW" ),
    THURROCK ( "THR" ),
    TORBAY ( "TOB" ),
    WARRINGTON ( "WRT" ),
    WEST_BERKSHIRE ( "WBK" ),
    WILTSHIRE ( "WIL" ),
    WINDSOR_AND_MAIDENHEAD ( "WNM" ),
    WOKINGHAM ( "WOK" ),
    YORK ( "YOR" ),
    ANTRIM_AND_NEWTOWNABBEY ( "ANN" ),
    ARDS_AND_NORTH_DOWN ( "AND" ),
    ARMAGH_BANBRIDGE_AND_CRAIGAVON ( "ABC" ),
    BELFAST ( "BFS" ),
    CAUSEWAY_COAST_AND_GLENS ( "CCG" ),
    DERRY_AND_STRABANE ( "DRS" ),
    FERMANAGH_AND_OMAGH ( "FMO" ),
    LISBURN_AND_CASTLEREAGH ( "LBC" ),
    MID_AND_EAST_ANTRIM ( "MEA" ),
    MID_ULSTER ( "MUL" ),
    NEWRY_MOURNE_AND_DOWN ( "NMD" ),
    ABERDEEN_CITY ( "ABE" ),
    ABERDEENSHIRE ( "ABD" ),
    ANGUS ( "ANS" ),
    ARGYLL_AND_BUTE ( "AGB" ),
    CLACKMANNANSHIRE ( "CLK" ),
    DUMFRIES_AND_GALLOWAY ( "DGY" ),
    DUNDEE_CITY ( "DND" ),
    EAST_AYRSHIRE ( "EAY" ),
    EAST_DUNBARTONSHIRE ( "EDU" ),
    EAST_LOTHIAN ( "ELN" ),
    EAST_RENFREWSHIRE ( "ERW" ),
    EDINBURGH_CITY_OF ( "EDH" ),
    EILEAN_SIAR ( "ELS" ),
    FALKIRK ( "FAL" ),
    FIFE ( "FIF" ),
    GLASGOW_CITY ( "GLG" ),
    HIGHLAND ( "HLD" ),
    INVERCLYDE ( "IVC" ),
    MIDLOTHIAN ( "MLN" ),
    MORAY ( "MRY" ),
    NORTH_AYRSHIRE ( "NAY" ),
    NORTH_LANARKSHIRE ( "NLK" ),
    ORKNEY_ISLANDS ( "ORK" ),
    PERTH_AND_KINROSS ( "PKN" ),
    RENFREWSHIRE ( "RFW" ),
    SCOTTISH_BORDERS_THE ( "SCB" ),
    SHETLAND_ISLANDS ( "ZET" ),
    SOUTH_AYRSHIRE ( "SAY" ),
    SOUTH_LANARKSHIRE ( "SLK" ),
    STIRLING ( "STG" ),
    WEST_DUNBARTONSHIRE ( "WDU" ),
    WEST_LOTHIAN ( "WLN" ),
    BLAENAU_GWENT ( "BGW" ),
    BRIDGEND ( "BGE" ),
    CAERPHILLY ( "CAY" ),
    CARDIFF ( "CRF" ),
    CARMARTHENSHIRE ( "CMN" ),
    CEREDIGION ( "CGN" ),
    CONWY ( "CWY" ),
    DENBIGHSHIRE ( "DEN" ),
    FLINTSHIRE ( "FLN" ),
    GWYNEDD ( "GWN" ),
    ISLE_OF_ANGLESEY ( "AGY" ),
    MERTHYR_TYDFIL ( "MTY" ),
    MONMOUTHSHIRE ( "MON" ),
    NEATH_PORT_TALBOT ( "NTL" ),
    NEWPORT ( "NWP" ),
    PEMBROKESHIRE ( "PEM" ),
    POWYS ( "POW" ),
    RHONDDA_CYNON_TAFF ( "RCT" ),
    SWANSEA ( "SWA" ),
    TORFAEN ( "TOF" ),
    VALE_OF_GLAMORGAN_THE ( "VGL" ),
    WREXHAM ( "WRX" );

    private String shortValue;
//    private String longValue;

    private COUNTY_ENGLAND(String shortValue) {
        this.shortValue = shortValue;
    }

//    private EMaritalStatus(String shortValue, String longValue ) {
//        this.shortValue = shortValue;
//        this.longValue = longValue;
//    }

    public String getShortValue() {
        return  shortValue;
    }

//    public String getLongValue() {
//        return longValue;
//    }

    public static String getShortValueByLongValue(String longValue) {
        for (COUNTY_ENGLAND value : COUNTY_ENGLAND.values()) {
            if ( value.name().equalsIgnoreCase(longValue)) {
                return  value.getShortValue();
            }
        }
        return null;
    }
    
}
