
Feature: Cal Quote Verification

  Background:
    Given user creates a quote

  Scenario Outline: Cal Quote
#    And user selects <BorrowerNumber> as number of borrowers
# Single Borrower or Joint Borrower
    And user clicks <BorrowerNumber> as number of borrowers
#    And user selects <MortgageType> as mortgage type
# First Time Buyer or Mover
    And user clicks <MortgageType> as mortgage type
    And user types <BorrowerAge> as age
    And user types <PartnerAge> as partner's age
    And user selects <BorrowerMaritalStatus> as marital status
    And user types <BorrowerTotalDependents> as total of dependents
    And user selects <BorrowerIncomeType> as income type
    And user types <BorrowerIncomeAmount> as income amount
    And user selects <PartnerIncomeType> as partner's income type
    And user types <PartnerIncomeAmount> as partner's income amount
    And user types <MonthlyCreditCommitments> as monthly credit commitments
    When user clicks "GET MY QUOTE"
    And user is<isEligible> eligible to borrow at this time
    Then user could buy a home up to the value of <MaxLoanAmount> euros, should pay monthly <MonthlyPayment> euros and should get a minimum deposit value of <MinimumDeposit> euros
#    And user could buy a home up to the value of <MaxLoanAmount> euros
#    And user should pay monthly <MonthlyPayment> euros
#    And user should get a minimum deposit value of <MinimumDeposit> euros

    Examples:
      | BorrowerNumber    | MortgageType        | BorrowerAge | PartnerAge | BorrowerMaritalStatus                | BorrowerTotalDependents | BorrowerIncomeType        | BorrowerIncomeAmount | PartnerIncomeType         | PartnerIncomeAmount | MonthlyCreditCommitments | isEligible | MaxLoanAmount                                     | MonthlyPayment | MinimumDeposit |
      | two borrowers     | first-time buyer(s) | 20          | 20         | separated                            | 1                       | an employee               | 150000               | an employee               | 150000              | 0                        |            | 1050000                                           | 4969           | 350000         |
      | two borrowers     | first-time buyer(s) | 20          | 20         | separated                            | 2                       | an employee               | 100000               | a civil servant           | 100000              | 100                      |            | 700000                                            | 3313           | 147500         |
#      | two borrowers     | first-time buyer(s) | 20          | 20         | separated                            | 3                       | an employee               | 65000                | not in paid work just now | 0                   | 0                        |            | 181445                                            | 559            | 13127          |
      | two borrowers     | first-time buyer(s) | 20          | 20         | separated                            | 0                       | an employee               | 85000                | self employed             | 75000               | 200                      |            | 560000                                            | 2650           | 112500         |
      | two borrowers     | first-time buyer(s) | 20          | 20         | separated                            | 0                       | a civil servant           | 2000000              | an employee               | 250000              | 240                      |            | 7875000                                           | 2825000        | 37269          |
      | two borrowers     | first-time buyer(s) | 20          | 20         | separated                            | 0                       | self employed             | 100000               | an employee               | 100000              | 230                      |            | 700000                                            | 3313           | 155975         |
#      | two borrowers     | first-time buyer(s) | 20          | 20         | separated                            | 2                       | not in paid work just now | 0                    | an employee               | 45000               | 1000                     |            | 108066                                            | 745            | 13208          |
#      | two borrowers     | first-time buyer(s) | 20          | 20         | separated                            | 1                       | not in paid work just now | 0                    | not in paid work just now | 0                   | 0                        | n't        |                                                   |                |                |
      | two borrowers     | first-time buyer(s) | 25          | 25         | married/civil partner(s)             | 1                       | an employee               | 150000               | an employee               | 150000              | 0                        |            | 1050000                                           | 4969           | 368000         |
      | two borrowers     | first-time buyer(s) | 25          | 25         | married/civil partner(s)             | 2                       | an employee               | 100000               | a civil servant           | 100000              | 100                      |            | 700000                                            | 3313           | 155975         |
      | two borrowers     | first-time buyer(s) | 25          | 25         | married/civil partner(s)             | 0                       | an employee               | 85000                | self employed             | 75000               | 200                      |            | 560000                                            | 2650           | 119225         |
#      | two borrowers     | first-time buyer(s) | 25          | 25         | married/civil partner(s)             | 3                       | an employee               | 65000                | not in paid work just now | 0                   | 0                        |            | 165733                                            | 1077           | 20256          |
      | two borrowers     | first-time buyer(s) | 25          | 25         | married/civil partner(s)             | 0                       | a civil servant           | 2000000              | an employee               | 250000              | 240                      |            | 7875000                                           | 37269          | 2825000        |
      | two borrowers     | first-time buyer(s) | 25          | 25         | married/civil partner(s)             | 0                       | self employed             | 100000               | an employee               | 100000              | 230                      |            | 700000                                            | 3313           | 155975         |
#      | two borrowers     | first-time buyer(s) | 25          | 25         | married/civil partner(s)             | 2                       | not in paid work just now | 0                    | an employee               | 45000               | 1000                     |            | 60478                                             | 745            | 7392           |
#      | two borrowers     | first-time buyer(s) | 25          | 25         | married/civil partner(s)             | 1                       | not in paid work just now | 0                    | not in paid work just now | 0                   | 0                        | n't        |                                                   |                |                |
      | two borrowers     | first-time buyer(s) | 30          | 30         | divorced/dissolved civil partnership | 1                       | an employee               | 150000               | an employee               | 150000              | 0                        |            | 1050000                                           | 4969           | 368000         |
      | two borrowers     | first-time buyer(s) | 30          | 30         | divorced/dissolved civil partnership | 2                       | an employee               | 100000               | a civil servant           | 100000              | 100                      |            | 700000                                            | 3313           | 155975         |
      | two borrowers     | first-time buyer(s) | 30          | 30         | divorced/dissolved civil partnership | 0                       | an employee               | 85000                | self employed             | 75000               | 200                      |            | 560000                                            | 2650           | 119225         |
#      | two borrowers     | first-time buyer(s) | 30          | 30         | divorced/dissolved civil partnership | 3                       | an employee               | 65000                | not in paid work just now | 0                   | 0                        |            | 118146                                            | 1077           | 14440          |
      | two borrowers     | first-time buyer(s) | 30          | 30         | divorced/dissolved civil partnership | 0                       | a civil servant           | 2000000              | an employee               | 250000              | 240                      |            | 7875000                                           | 37269          | 2825000        |
      | two borrowers     | first-time buyer(s) | 30          | 30         | divorced/dissolved civil partnership | 0                       | self employed             | 100000               | an employee               | 100000              | 230                      |            | 700000                                            | 3313           | 155975         |
#      | two borrowers     | first-time buyer(s) | 30          | 30         | divorced/dissolved civil partnership | 2                       | not in paid work just now | 0                    | an employee               | 45000               | 1000                     |            | 108066                                            | 745            | 13208          |
#      | two borrowers     | first-time buyer(s) | 30          | 30         | divorced/dissolved civil partnership | 1                       | not in paid work just now | 0                    | not in paid work just now | 0                   | 0                        | n't        |                                                   |                |                |
      | two borrowers     | first-time buyer(s) | 35          | 35         | widowed                              | 1                       | an employee               | 150000               | an employee               | 150000              | 0                        |            | 1050000                                           | 4969           | 368000         |
      | two borrowers     | first-time buyer(s) | 35          | 35         | widowed                              | 2                       | an employee               | 100000               | a civil servant           | 100000              | 100                      |            | 700000                                            | 3313           | 155975         |
      | two borrowers     | first-time buyer(s) | 35          | 35         | widowed                              | 0                       | an employee               | 85000                | self employed             | 75000               | 200                      |            | 560000                                            | 2650           | 119225         |
#      | two borrowers     | first-time buyer(s) | 35          | 35         | widowed                              | 3                       | an employee               | 65000                | not in paid work just now | 0                   | 0                        |            | 140905                                            | 1077           | 17222          |
      | two borrowers     | first-time buyer(s) | 35          | 35         | widowed                              | 0                       | a civil servant           | 2000000              | an employee               | 250000              | 240                      |            | 7875000                                           | 37269          | 2825000        |
      | two borrowers     | first-time buyer(s) | 35          | 35         | widowed                              | 0                       | self employed             | 100000               | an employee               | 100000              | 230                      |            | 700000                                            | 3313           | 155975         |
#      | two borrowers     | first-time buyer(s) | 35          | 35         | widowed                              | 2                       | not in paid work just now | 0                    | an employee               | 45000               | 1000                     |            | 85307                                             | 745            | 10426          |
#      | two borrowers     | first-time buyer(s) | 35          | 35         | widowed                              | 1                       | not in paid work just now | 0                    | not in paid work just now | 0                   | 0                        | n't        |                                                   |                |                |
      | two borrowers     | first-time buyer(s) | 35          | 35         | married/civil partner(s)             | 1                       | an employee               | 150000               | an employee               | 150000              | 0                        |            | 1050000                                           | 4969           | 368000         |
      | two borrowers     | first-time buyer(s) | 35          | 35         | married/civil partner(s)             | 2                       | an employee               | 100000               | a civil servant           | 100000              | 100                      |            | 700000                                            | 3313           | 155975         |
      | two borrowers     | first-time buyer(s) | 35          | 35         | married/civil partner(s)             | 0                       | an employee               | 85000                | self employed             | 75000               | 200                      |            | 560000                                            | 2650           | 119225         |
#      | two borrowers     | first-time buyer(s) | 35          | 35         | married/civil partner(s)             | 3                       | an employee               | 65000                | not in paid work just now | 0                   | 0                        |            | 165733                                            | 784            | 20256          |
      | two borrowers     | first-time buyer(s) | 35          | 35         | married/civil partner(s)             | 0                       | a civil servant           | 2000000              | an employee               | 250000              | 240                      |            | 7875000                                           | 37269          | 2825000        |
      | two borrowers     | first-time buyer(s) | 35          | 35         | married/civil partner(s)             | 0                       | self employed             | 100000               | an employee               | 100000              | 230                      |            | 700000                                            | 3313           | 155975         |
#      | two borrowers     | first-time buyer(s) | 35          | 35         | married/civil partner(s)             | 2                       | not in paid work just now | 0                    | an employee               | 45000               | 1000                     |            | 60478                                             | 745            | 7392           |
#      | two borrowers     | first-time buyer(s) | 35          | 35         | married/civil partner(s)             | 1                       | not in paid work just now | 0                    | not in paid work just now | 0                   | 0                        | n't        |                                                   |                |                |
      | two borrowers     | mover(s)            | 20          | 20         | separated                            | 1                       | an employee               | 150000               | an employee               | 150000              | 0                        |            | 1050000                                           | 5320           | 368000         |
      | two borrowers     | mover(s)            | 20          | 20         | separated                            | 2                       | an employee               | 100000               | a civil servant           | 100000              | 100                      |            | 700000                                            | 3547           | 183750         |
      | two borrowers     | mover(s)            | 20          | 20         | separated                            | 0                       | an employee               | 85000                | self employed             | 75000               | 200                      |            | 56000                                             | 2837           | 147000         |
#      | two borrowers     | mover(s)            | 20          | 20         | separated                            | 3                       | an employee               | 65000                | not in paid work just now | 0                   | 0                        |            | 11292825                                          | 1153           | 29644          |
      | two borrowers     | mover(s)            | 20          | 20         | separated                            | 0                       | a civil servant           | 2000000              | an employee               | 250000              | 240                      |            | 7875000                                           | 39901          | 2825000        |
      | two borrowers     | mover(s)            | 20          | 20         | separated                            | 0                       | self employed             | 100000               | an employee               | 100000              | 230                      |            | 700000                                            | 3547           | 183750         |
#      | two borrowers     | mover(s)            | 20          | 20         | separated                            | 2                       | not in paid work just now | 0                    | an employee               | 45000               | 1000                     |            | 103293                                            | 798            | 27114          |
#      | two borrowers     | mover(s)            | 20          | 20         | separated                            | 1                       | not in paid work just now | 0                    | not in paid work just now | 0                   | 0                        | n't        |                                                   |                |                |
      | two borrowers     | mover(s)            | 25          | 25         | married/civil partner(s)             | 1                       | an employee               | 150000               | an employee               | 150000              | 0                        |            | 1050000                                           | 5320           | 368000         |
      | two borrowers     | mover(s)            | 25          | 25         | married/civil partner(s)             | 2                       | an employee               | 100000               | a civil servant           | 100000              | 100                      |            | 700000                                            | 3547           | 183750         |
      | two borrowers     | mover(s)            | 25          | 25         | married/civil partner(s)             | 0                       | an employee               | 85000                | self employed             | 75000               | 200                      |            | 560000                                            | 2837           | 147000         |
#      | two borrowers     | mover(s)            | 25          | 25         | married/civil partner(s)             | 3                       | an employee               | 65000                | not in paid work just now | 0                   | 0                        |            | 158414                                            | 1153           | 41584          |
      | two borrowers     | mover(s)            | 25          | 25         | married/civil partner(s)             | 0                       | a civil servant           | 2000000              | an employee               | 250000              | 240                      |            | 7875000                                           | 39901          | 2825000        |
      | two borrowers     | mover(s)            | 25          | 25         | married/civil partner(s)             | 0                       | self employed             | 100000               | an employee               | 100000              | 230                      |            | 700000                                            | 3547           | 183750         |
#      | two borrowers     | mover(s)            | 25          | 25         | married/civil partner(s)             | 2                       | not in paid work just now | 0                    | an employee               | 45000               | 1000                     |            | 57808                                             | 798            | 15174          |
#      | two borrowers     | mover(s)            | 25          | 25         | married/civil partner(s)             | 1                       | not in paid work just now | 0                    | not in paid work just now | 0                   | 0                        | n't        |                                                   |                |                |
      | two borrowers     | mover(s)            | 30          | 30         | divorced/dissolved civil partnership | 1                       | an employee               | 150000               | an employee               | 150000              | 0                        |            | 1050000                                           | 5320           | 368000         |
      | two borrowers     | mover(s)            | 30          | 30         | divorced/dissolved civil partnership | 2                       | an employee               | 100000               | a civil servant           | 100000              | 100                      |            | 700000                                            | 3547           | 183750         |
      | two borrowers     | mover(s)            | 30          | 30         | divorced/dissolved civil partnership | 0                       | an employee               | 85000                | self employed             | 75000               | 200                      |            | 560000                                            | 2837           | 147000         |
#      | two borrowers     | mover(s)            | 30          | 30         | divorced/dissolved civil partnership | 3                       | an employee               | 65000                | not in paid work just now | 0                   | 0                        |            | 112928                                            | 1153           | 29644          |
      | two borrowers     | mover(s)            | 30          | 30         | divorced/dissolved civil partnership | 0                       | a civil servant           | 2000000              | an employee               | 250000              | 240                      |            | 7875000                                           | 39901          | 2825000        |
      | two borrowers     | mover(s)            | 30          | 30         | divorced/dissolved civil partnership | 0                       | self employed             | 100000               | an employee               | 100000              | 230                      |            | 700000                                            | 3547           | 183750         |
#      | two borrowers     | mover(s)            | 30          | 30         | divorced/dissolved civil partnership | 2                       | not in paid work just now | 0                    | an employee               | 45000               | 1000                     |            | 103293                                            | 798            | 27114          |
#      | two borrowers     | mover(s)            | 30          | 30         | divorced/dissolved civil partnership | 1                       | not in paid work just now | 0                    | not in paid work just now | 0                   | 0                        | n't        |                                                   |                |                |
      | two borrowers     | mover(s)            | 35          | 35         | widowed                              |                         | an employee               | 150000               | an employee               | 150000              | 0                        |            | 577500                                            | 2926           | 151594         |
      | two borrowers     | mover(s)            | 35          | 35         | widowed                              | 2                       | an employee               | 100000               | a civil servant           | 100000              | 100                      |            | 700000                                            | 3547           | 183750         |
      | two borrowers     | mover(s)            | 45          | 45         | widowed                              | 0                       | an employee               | 85000                | self employed             | 75000               | 200                      |            | 560000                                            | 3113           | 147000         |
#      | two borrowers     | mover(s)            | 45          | 55         | widowed                              | 3                       | an employee               | 65000                | not in paid work just now | 0                   | 0                        |            | 92941                                             | 1740           | 24397          |
      | two borrowers     | mover(s)            | 55          | 50         | widowed                              | 0                       | a civil servant           | 2000000              | an employee               | 250000              | 240                      |            | 7875000                                           | 60243          | 2825000        |
      | two borrowers     | mover(s)            | 46          | 48         | widowed                              | 0                       | self employed             | 100000               | an employee               | 100000              | 230                      |            | 700000                                            | 4182           | 183750         |
#      | two borrowers     | mover(s)            | 35          | 35         | widowed                              | 2                       | not in paid work just now | 0                    | an employee               | 45000               | 1000                     | n't        |                                                   |                |                |
#      | two borrowers     | mover(s)            | 35          | 35         | widowed                              |                         | not in paid work just now | 0                    | not in paid work just now | 0                   | 0                        | n't        |                                                   |                |                |
      | two borrowers     | mover(s)            | 45          | 45         | married/civil partner(s)             | 1                       | an employee               | 150000               | an employee               | 150000              | 0                        |            | 1050000                                           | 5836           | 368000         |
      | two borrowers     | mover(s)            | 55          | 55         | married/civil partner(s)             | 2                       | an employee               | 100000               | a civil servant           | 100000              | 100                      |            | 695367                                            | 5355           | 182534         |
      | two borrowers     | mover(s)            | 65          | 45         | married/civil partner(s)             | 0                       | an employee               | 85000                | self employed             | 75000               | 200                      |            | 255465                                            | 10440          | 67060          |
#      | two borrowers     | mover(s)            | 35          | 65         | married/civil partner(s)             | 3                       | an employee               | 65000                | not in paid work just now | 0                   | 0                        |            | 51174                                             | 954            | 13433          |
      | two borrowers     | mover(s)            | 55          | 20         | married/civil partner(s)             | 0                       | a civil servant           | 2000000              | an employee               | 250000              | 240                      |            | 7875000                                           | 60243          | 2825000        |
      | two borrowers     | mover(s)            | 55          | 60         | married/civil partner(s)             | 0                       | self employed             | 100000               | an employee               | 100000              | 230                      |            | 578476                                            | 7255           | 151850         |
#      | two borrowers     | mover(s)            | 45          | 55         | married/civil partner(s)             | 2                       | not in paid work just now | 0                    | an employee               | 45000               | 1000                     | n't        |                                                   |                |                |
#      | two borrowers     | mover(s)            | 89          | 90         | married/civil partner(s)             | 1                       | not in paid work just now | 0                    | not in paid work just now | 0                   | 0                        | n't        |                                                   |                |                |
      | a single borrower | first-time buyer(s) | 20          |            | separated                            | 1                       | an employee               | 100000               |                           |                     | 0                        |            | 350000                                            | 1656           | 64100          |
      | a single borrower | first-time buyer(s) | 35          |            | separated                            | 2                       | a civil servant           | 65000                |                           |                     | 100                      |            | 213669                                            | 1011           | 28313          |
      | a single borrower | first-time buyer(s) | 45          |            | separated                            | 0                       | self employed             | 89000                |                           |                     | 200                      |            | 230342                                            | 3228           | 32690          |
#      | a single borrower | first-time buyer(s) | 30          |            | separated                            | 3                       | not in paid work just now | 0                    |                           |                     | 0                        | n't        |                                                   |                |                |
      | a single borrower | first-time buyer(s) | 20          |            | married/civil partner(s)             | 0                       | an employee               | 100000               |                           |                     | 240                      |            | 350000                                            | 1656           | 64100          |
      | a single borrower | first-time buyer(s) | 35          |            | married/civil partner(s)             | 0                       | a civil servant           | 65000                |                           |                     | 230                      |            | 194220                                            | 919            | 23738          |
      | a single borrower | first-time buyer(s) | 45          |            | married/civil partner(s)             | 2                       | self employed             | 89000                |                           |                     | 1000                     |            | 137437                                            | 764            | 16798          |
#      | a single borrower | first-time buyer(s) | 30          |            | married/civil partner(s)             | 1                       | not in paid work just now | 0                    |                           |                     | 0                        | n't        |                                                   |                |                |
      | a single borrower | first-time buyer(s) | 20          |            | divorced/dissolved civil partnership | 1                       | an employee               | 100000               |                           |                     | 0                        |            | 350000                                            | 1656           | 64100          |
      | a single borrower | first-time buyer(s) | 35          |            | divorced/dissolved civil partnership | 2                       | a civil servant           | 65000                |                           |                     | 100                      |            | 213669                                            | 1011           | 28313          |
      | a single borrower | first-time buyer(s) | 45          |            | divorced/dissolved civil partnership | 0                       | self employed             | 89000                |                           |                     | 200                      |            | 311500                                            | 1731           | 53994          |
#      | a single borrower | first-time buyer(s) | 30          |            | divorced/dissolved civil partnership | 3                       | not in paid work just now | 0                    |                           |                     | 0                        | n't        |                                                   |                |                |
      | a single borrower | first-time buyer(s) | 20          |            | widowed                              | 0                       | an employee               | 100000               |                           |                     | 240                      |            | 350000                                            | 1656           | 64100          |
      | a single borrower | first-time buyer(s) | 35          |            | widowed                              | 0                       | a civil servant           | 65000                |                           |                     | 230                      |            | 227500                                            | 1077           | 31944          |
      | a single borrower | first-time buyer(s) | 45          |            | widowed                              | 2                       | self employed             | 89000                |                           |                     | 1000                     |            | 230002                                            | 1731           | 32600          |
#      | a single borrower | first-time buyer(s) | 30          |            | widowed                              |                         | not in paid work just now | 0                    |                           |                     | 0                        | n't        |                                                   |                |                |
      | a single borrower | mover(s)            | 20          |            | separated                            | 1                       | an employee               | 100000               |                           |                     | 0                        |            | 350000                                            | 1773           | 91875          |
      | a single borrower | mover(s)            | 35          |            | separated                            | 2                       | a civil servant           | 65000                |                           |                     | 100                      |            | 204232                                            | 1035           | 53611          |
      | a single borrower | mover(s)            | 45          |            | separated                            | 0                       | self employed             | 89000                |                           |                     | 200                      |            | 311500                                            | 1731           | 81769          |
#      | a single borrower | mover(s)            | 30          |            | separated                            | 3                       | not in paid work just now | 0                    |                           |                     | 0                        | n't        |                                                   |                |                |
      | a single borrower | mover(s)            | 20          |            | married/civil partner(s)             | 0                       | an employee               | 100000               |                           |                     | 240                      |            | 350000                                            | 1773           | 91875          |
      | a single borrower | mover(s)            | 35          |            | married/civil partner(s)             | 0                       | a civil servant           | 65000                |                           |                     | 230                      |            | 185643                                            | 941            | 48731          |
      | a single borrower | mover(s)            | 45          |            | married/civil partner(s)             | 2                       | self employed             | 89000                |                           |                     | 1000                     |            | 137437                                            | 764            | 36077          |
#      | a single borrower | mover(s)            | 30          |            | married/civil partner(s)             | 1                       | not in paid work just now | 0                    |                           |                     | 0                        | n't        |                                                   |                |                |
      | a single borrower | mover(s)            | 20          |            | divorced/dissolved civil partnership | 1                       | an employee               | 190000               |                           |                     | 0                        |            | 665000                                            | 3369           | 174563         |
      | a single borrower | mover(s)            | 35          |            | divorced/dissolved civil partnership | 2                       | a civil servant           | 65000                |                           |                     | 100                      |            | 204232                                            | 1035           | 53611          |
      | a single borrower | mover(s)            | 45          |            | divorced/dissolved civil partnership | 0                       | self employed             | 89000                |                           |                     | 200                      |            | 311500                                            | 1731           | 81769          |
#      | a single borrower | mover(s)            | 30          |            | divorced/dissolved civil partnership | 3                       | not in paid work just now | 0                    |                           |                     | 0                        | n't        |                                                   |                |                |
      | a single borrower | mover(s)            | 20          |            | widowed                              | 0                       | an employee               | 190000               |                           |                     | 240                      |            | 665000                                            | 3369           | 174563         |
      | a single borrower | mover(s)            | 35          |            | widowed                              | 0                       | a civil servant           | 65000                |                           |                     | 230                      |            | 227500                                            | 1153           | 59719          |
      | a single borrower | mover(s)            | 45          |            | widowed                              | 2                       | self employed             | 89000                |                           |                     | 1000                     |            | 230002                                            | 1731           | 60375          |
#      | a single borrower | mover(s)            | 30          |            | widowed                              |                         | not in paid work just now | 0                    |                           |                     | 0                        | n't        |                                                   |                |                |