Feature: Cal Quote - Two Borrowers First Time Buyers

  Background:
    Given user creates a quote

  Scenario Outline: Cal Quote
    And user selects <BorrowerNumber> as number of borrowers
    And user selects <MortgageType> as mortgage type
    And user types <BorrowerAge> as age
    And user types <PartnerAge> as partner's age
    And user selects <BorrowerMaritalStatus> as marital status
    And user types <BorrowerTotalDependents> as total of dependents
    And user selects <BorrowerIncomeType> as income type
    And user types <BorrowerIncomeAmount> as income amount
    And user selects <PartnerIncomeType> as partner's income type
    And user types <PartnerIncomeAmount> as partner's income amount
    And user types <MonthlyCreditCommitments> as monthly credit commitments
    When user clicks "GET MY QUOTE"
    And user is<isEligible> eligible to borrow at this time
    Then user could buy a home up to the value of <MaxLoanAmount> euros
    And user should pay monthly <MonthlyPayment> euros
    And user should get a minimum deposit value of <MinimumDeposit> euros

    Examples:
      | BorrowerNumber    | MortgageType        | BorrowerAge | PartnerAge | BorrowerMaritalStatus                | BorrowerTotalDependents | BorrowerIncomeType        | BorrowerIncomeAmount | PartnerIncomeType         | PartnerIncomeAmount | MonthlyCreditCommitments | isEligible | MaxLoanAmount                                     | MonthlyPayment | MinimumDeposit |
      | two borrowers     | first-time buyer(s) | 20          | 20         | separated                            | 1                       | an employee               | 150000               | an employee               | 150000              | 0                        |            | 1050000                                           | 4969           | 350000         |
      | two borrowers     | first-time buyer(s) | 20          | 20         | separated                            | 2                       | an employee               | 100000               | a civil servant           | 100000              | 100                      |            | 700000                                            | 3313           | 147500         |
      | two borrowers     | first-time buyer(s) | 20          | 20         | separated                            | 3                       | an employee               | 65000                | not in paid work just now | 0                   | 0                        |            | 181445                                            | 559            | 13127          |
      | two borrowers     | first-time buyer(s) | 20          | 20         | separated                            | 0                       | an employee               | 85000                | self employed             | 75000               | 200                      |            | 560000                                            | 2650           | 112500         |
      | two borrowers     | first-time buyer(s) | 20          | 20         | separated                            | 0                       | a civil servant           | 2000000              | an employee               | 250000              | 240                      |            | 7875000                                           | 2825000        | 37269          |
      | two borrowers     | first-time buyer(s) | 20          | 20         | separated                            | 0                       | self employed             | 100000               | an employee               | 100000              | 230                      |            | 700000                                            | 3313           | 155975         |
      | two borrowers     | first-time buyer(s) | 20          | 20         | separated                            | 2                       | not in paid work just now | 0                    | an employee               | 45000               | 1000                     |            | 108066                                            | 745            | 13208          |
      | two borrowers     | first-time buyer(s) | 20          | 20         | separated                            | 1                       | not in paid work just now | 0                    | not in paid work just now | 0                   | 0                        | n't        |                                                   |                |                |
      | two borrowers     | first-time buyer(s) | 25          | 25         | married/civil partner(s)             | 1                       | an employee               | 150000               | an employee               | 150000              | 0                        |            | 1050000                                           | 4969           | 368000         |
      | two borrowers     | first-time buyer(s) | 25          | 25         | married/civil partner(s)             | 2                       | an employee               | 100000               | a civil servant           | 100000              | 100                      |            | 700000                                            | 3313           | 155975         |
      | two borrowers     | first-time buyer(s) | 25          | 25         | married/civil partner(s)             | 0                       | an employee               | 85000                | self employed             | 75000               | 200                      |            | 560000                                            | 2650           | 119225         |
      | two borrowers     | first-time buyer(s) | 25          | 25         | married/civil partner(s)             | 3                       | an employee               | 65000                | not in paid work just now | 0                   | 0                        |            | 165733                                            | 1077           | 20256          |
      | two borrowers     | first-time buyer(s) | 25          | 25         | married/civil partner(s)             | 0                       | a civil servant           | 2000000              | an employee               | 250000              | 240                      |            | 7875000                                           | 37269          | 2825000        |
      | two borrowers     | first-time buyer(s) | 25          | 25         | married/civil partner(s)             | 0                       | self employed             | 100000               | an employee               | 100000              | 230                      |            | 700000                                            | 3313           | 155975         |
      | two borrowers     | first-time buyer(s) | 25          | 25         | married/civil partner(s)             | 2                       | not in paid work just now | 0                    | an employee               | 45000               | 1000                     |            | 60478                                             | 745            | 7392           |
      | two borrowers     | first-time buyer(s) | 25          | 25         | married/civil partner(s)             | 1                       | not in paid work just now | 0                    | not in paid work just now | 0                   | 0                        | n't        |                                                   |                |                |
      | two borrowers     | first-time buyer(s) | 30          | 30         | divorced/dissolved civil partnership | 1                       | an employee               | 150000               | an employee               | 150000              | 0                        |            | 1050000                                           | 4969           | 368000         |
      | two borrowers     | first-time buyer(s) | 30          | 30         | divorced/dissolved civil partnership | 2                       | an employee               | 100000               | a civil servant           | 100000              | 100                      |            | 700000                                            | 3313           | 155975         |
      | two borrowers     | first-time buyer(s) | 30          | 30         | divorced/dissolved civil partnership | 0                       | an employee               | 85000                | self employed             | 75000               | 200                      |            | 560000                                            | 2650           | 119225         |
      | two borrowers     | first-time buyer(s) | 30          | 30         | divorced/dissolved civil partnership | 3                       | an employee               | 65000                | not in paid work just now | 0                   | 0                        |            | 118146                                            | 1077           | 14440          |
      | two borrowers     | first-time buyer(s) | 30          | 30         | divorced/dissolved civil partnership | 0                       | a civil servant           | 2000000              | an employee               | 250000              | 240                      |            | 7875000                                           | 37269          | 2825000        |
      | two borrowers     | first-time buyer(s) | 30          | 30         | divorced/dissolved civil partnership | 0                       | self employed             | 100000               | an employee               | 100000              | 230                      |            | 700000                                            | 3313           | 155975         |
      | two borrowers     | first-time buyer(s) | 30          | 30         | divorced/dissolved civil partnership | 2                       | not in paid work just now | 0                    | an employee               | 45000               | 1000                     |            | 108066                                            | 745            | 13208          |
      | two borrowers     | first-time buyer(s) | 30          | 30         | divorced/dissolved civil partnership | 1                       | not in paid work just now | 0                    | not in paid work just now | 0                   | 0                        | n't        |                                                   |                |                |
      | two borrowers     | first-time buyer(s) | 35          | 35         | widowed                              | 1                       | an employee               | 150000               | an employee               | 150000              | 0                        |            | 1050000                                           | 4969           | 368000         |
      | two borrowers     | first-time buyer(s) | 35          | 35         | widowed                              | 2                       | an employee               | 100000               | a civil servant           | 100000              | 100                      |            | 700000                                            | 3313           | 155975         |
      | two borrowers     | first-time buyer(s) | 35          | 35         | widowed                              | 0                       | an employee               | 85000                | self employed             | 75000               | 200                      |            | 560000                                            | 2650           | 119225         |
      | two borrowers     | first-time buyer(s) | 35          | 35         | widowed                              | 3                       | an employee               | 65000                | not in paid work just now | 0                   | 0                        |            | 140905                                            | 1077           | 17222          |
      | two borrowers     | first-time buyer(s) | 35          | 35         | widowed                              | 0                       | a civil servant           | 2000000              | an employee               | 250000              | 240                      |            | 7875000                                           | 37269          | 2825000        |
      | two borrowers     | first-time buyer(s) | 35          | 35         | widowed                              | 0                       | self employed             | 100000               | an employee               | 100000              | 230                      |            | 700000                                            | 3313           | 155975         |
      | two borrowers     | first-time buyer(s) | 35          | 35         | widowed                              | 2                       | not in paid work just now | 0                    | an employee               | 45000               | 1000                     |            | 85307                                             | 745            | 10426          |
      | two borrowers     | first-time buyer(s) | 35          | 35         | widowed                              | 1                       | not in paid work just now | 0                    | not in paid work just now | 0                   | 0                        | n't        |                                                   |                |                |
      | two borrowers     | first-time buyer(s) | 35          | 35         | married/civil partner(s)             | 1                       | an employee               | 150000               | an employee               | 150000              | 0                        |            | 1050000                                           | 4969           | 368000         |
      | two borrowers     | first-time buyer(s) | 35          | 35         | married/civil partner(s)             | 2                       | an employee               | 100000               | a civil servant           | 100000              | 100                      |            | 700000                                            | 3313           | 155975         |
      | two borrowers     | first-time buyer(s) | 35          | 35         | married/civil partner(s)             | 0                       | an employee               | 85000                | self employed             | 75000               | 200                      |            | 560000                                            | 2650           | 119225         |
      | two borrowers     | first-time buyer(s) | 35          | 35         | married/civil partner(s)             | 3                       | an employee               | 65000                | not in paid work just now | 0                   | 0                        |            | 165733                                            | 784            | 20256          |
      | two borrowers     | first-time buyer(s) | 35          | 35         | married/civil partner(s)             | 0                       | a civil servant           | 2000000              | an employee               | 250000              | 240                      |            | 7875000                                           | 37269          | 2825000        |
      | two borrowers     | first-time buyer(s) | 35          | 35         | married/civil partner(s)             | 0                       | self employed             | 100000               | an employee               | 100000              | 230                      |            | 700000                                            | 3313           | 155975         |
      | two borrowers     | first-time buyer(s) | 35          | 35         | married/civil partner(s)             | 2                       | not in paid work just now | 0                    | an employee               | 45000               | 1000                     |            | 60478                                             | 745            | 7392           |
      | two borrowers     | first-time buyer(s) | 35          | 35         | married/civil partner(s)             | 1                       | not in paid work just now | 0                    | not in paid work just now | 0                   | 0                        | n't        |                                                   |                |                |
