/*
CountyState2

root:c:w:pnlCounty:c:w:pnlEnglandCounty:c:w:cmbCountyState2:v
<option selected="selected" value="">Choose One</option>
<option value="BKM">Buckinghamshire</option>
<option value="CAM">Cambridgeshire</option>
<option value="CMA">Cumbria</option>
<option value="DBY">Derbyshire</option>
<option value="DEV">Devon</option>
<option value="DOR">Dorset</option>
<option value="ESX">East Sussex</option>
<option value="ESS">Essex</option>
<option value="GLS">Gloucestershire</option>
<option value="HAM">Hampshire</option>
<option value="HRT">Hertfordshire</option>
<option value="KEN">Kent</option>
<option value="LAN">Lancashire</option>
<option value="LEC">Leicestershire</option>
<option value="LIN">Lincolnshire</option>
<option value="NFK">Norfolk</option>
<option value="NYK">North Yorkshire</option>
<option value="NTH">Northamptonshire</option>
<option value="NTT">Nottinghamshire</option>
<option value="OXF">Oxfordshire</option>
<option value="SOM">Somerset</option>
<option value="STS">Staffordshire</option>
<option value="SFK">Suffolk</option>
<option value="SRY">Surrey</option>
<option value="WAR">Warwickshire</option>
<option value="WSX">West Sussex</option>
<option value="WOR">Worcestershire</option>
<option value="LND">London, City of</option>
<option value="BDG">Barking and Dagenham</option>
<option value="BNE">Barnet</option>
<option value="BEX">Bexley</option>
<option value="BEN">Brent</option>
<option value="BRY">Bromley</option>
<option value="CMD">Camden</option>
<option value="CRY">Croydon</option>
<option value="EAL">Ealing</option>
<option value="ENF">Enfield</option>
<option value="GRE">Greenwich</option>
<option value="HCK">Hackney</option>
<option value="HMF">Hammersmith and Fulham</option>
<option value="HRY">Haringey</option>
<option value="HRW">Harrow</option>
<option value="HAV">Havering</option>
<option value="HIL">Hillingdon</option>
<option value="HNS">Hounslow</option>
<option value="ISL">Islington</option>
<option value="KEC">Kensington and Chelsea</option>
<option value="KTT">Kingston upon Thames</option>
<option value="LBH">Lambeth</option>
<option value="LEW">Lewisham</option>
<option value="MRT">Merton</option>
<option value="NWM">Newham</option>
<option value="RDB">Redbridge</option>
<option value="RIC">Richmond upon Thames</option>
<option value="SWK">Southwark</option>
<option value="STN">Sutton</option>
<option value="TWH">Tower Hamlets</option>
<option value="WFT">Waltham Forest</option>
<option value="WND">Wandsworth</option>
<option value="WSM">Westminster</option>
<option value="BNS">Barnsley</option>
<option value="BIR">Birmingham</option>
<option value="BOL">Bolton</option>
<option value="BRD">Bradford</option>
<option value="BUR">Bury</option>
<option value="CLD">Calderdale</option>
<option value="COV">Coventry</option>
<option value="DNC">Doncaster</option>
<option value="DUD">Dudley</option>
<option value="GAT">Gateshead</option>
<option value="KIR">Kirklees</option>
<option value="KWL">Knowsley</option>
<option value="LDS">Leeds</option>
<option value="LIV">Liverpool</option>
<option value="MAN">Manchester</option>
<option value="NET">Newcastle upon Tyne</option>
<option value="NTY">North Tyneside</option>
<option value="OLD">Oldham</option>
<option value="RCH">Rochdale</option>
<option value="ROT">Rotherham</option>
<option value="SHN">St. Helens</option>
<option value="SLF">Salford</option>
<option value="SAW">Sandwell</option>
<option value="SFT">Sefton</option>
<option value="SHF">Sheffield</option>
<option value="SOL">Solihull</option>
<option value="STY">South Tyneside</option>
<option value="SKP">Stockport</option>
<option value="SND">Sunderland</option>
<option value="TAM">Tameside</option>
<option value="TRF">Trafford</option>
<option value="WKF">Wakefield</option>
<option value="WLL">Walsall</option>
<option value="WGN">Wigan</option>
<option value="WRL">Wirral</option>
<option value="WLV">Wolverhampton</option>
<option value="BAS">Bath and North East Somerset</option>
<option value="BDF">Bedford</option>
<option value="BBD">Blackburn with Darwen</option>
<option value="BPL">Blackpool</option>
<option value="BMH">Bournemouth</option>
<option value="BRC">Bracknell Forest</option>
<option value="BNH">Brighton and Hove</option>
<option value="BST">Bristol, City of</option>
<option value="CBF">Central Bedfordshire</option>
<option value="CHE">Cheshire East</option>
<option value="CHW">Cheshire West and Chester</option>
<option value="CON">Cornwall</option>
<option value="DAL">Darlington</option>
<option value="DER">Derby</option>
<option value="DUR">Durham, County</option>
<option value="ERY">East Riding of Yorkshire</option>
<option value="HAL">Halton</option>
<option value="HPL">Hartlepool</option>
<option value="HEF">Herefordshire</option>
<option value="IOW">Isle of Wight</option>
<option value="IOS">Isles of Scilly</option>
<option value="KHL">Kingston upon Hull</option>
<option value="LCE">Leicester</option>
<option value="LUT">Luton</option>
<option value="MDW">Medway</option>
<option value="MDB">Middlesbrough</option>
<option value="MIK">Milton Keynes</option>
<option value="NEL">North East Lincolnshire</option>
<option value="NLN">North Lincolnshire</option>
<option value="NSM">North Somerset</option>
<option value="NBL">Northumberland</option>
<option value="NGM">Nottingham</option>
<option value="PTE">Peterborough</option>
<option value="PLY">Plymouth</option>
<option value="POL">Poole</option>
<option value="POR">Portsmouth</option>
<option value="RDG">Reading</option>
<option value="RCC">Redcar and Cleveland</option>
<option value="RUT">Rutland</option>
<option value="SHR">Shropshire</option>
<option value="SLG">Slough</option>
<option value="SGC">South Gloucestershire</option>
<option value="STH">Southampton</option>
<option value="SOS">Southend-on-Sea</option>
<option value="STT">Stockton-on-Tees</option>
<option value="STE">Stoke-on-Trent</option>
<option value="SWD">Swindon</option>
<option value="TFW">Telford and Wrekin</option>
<option value="THR">Thurrock</option>
<option value="TOB">Torbay</option>
<option value="WRT">Warrington</option>
<option value="WBK">West Berkshire</option>
<option value="WIL">Wiltshire</option>
<option value="WNM">Windsor and Maidenhead</option>
<option value="WOK">Wokingham</option>
<option value="YOR">York</option>
<option value="ANN">Antrim and Newtownabbey</option>
<option value="AND">Ards and North Down</option>
<option value="ABC">Armagh, Banbridge and Craigavon</option>
<option value="BFS">Belfast</option>
<option value="CCG">Causeway Coast and Glens</option>
<option value="DRS">Derry and Strabane</option>
<option value="FMO">Fermanagh and Omagh</option>
<option value="LBC">Lisburn and Castlereagh</option>
<option value="MEA">Mid and East Antrim</option>
<option value="MUL">Mid Ulster</option>
<option value="NMD">Newry, Mourne and Down</option>
<option value="ABE">Aberdeen City</option>
<option value="ABD">Aberdeenshire</option>
<option value="ANS">Angus</option>
<option value="AGB">Argyll and Bute</option>
<option value="CLK">Clackmannanshire</option>
<option value="DGY">Dumfries and Galloway</option>
<option value="DND">Dundee City</option>
<option value="EAY">East Ayrshire</option>
<option value="EDU">East Dunbartonshire</option>
<option value="ELN">East Lothian</option>
<option value="ERW">East Renfrewshire</option>
<option value="EDH">Edinburgh, City of</option>
<option value="ELS">Eilean Siar</option>
<option value="FAL">Falkirk</option>
<option value="FIF">Fife</option>
<option value="GLG">Glasgow City</option>
<option value="HLD">Highland</option>
<option value="IVC">Inverclyde</option>
<option value="MLN">Midlothian</option>
<option value="MRY">Moray</option>
<option value="NAY">North Ayrshire</option>
<option value="NLK">North Lanarkshire</option>
<option value="ORK">Orkney Islands</option>
<option value="PKN">Perth and Kinross</option>
<option value="RFW">Renfrewshire</option>
<option value="SCB">Scottish Borders, The</option>
<option value="ZET">Shetland Islands</option>
<option value="SAY">South Ayrshire</option>
<option value="SLK">South Lanarkshire</option>
<option value="STG">Stirling</option>
<option value="WDU">West Dunbartonshire</option>
<option value="WLN">West Lothian</option>
<option value="BGW">Blaenau Gwent</option>
<option value="BGE">Bridgend</option>
<option value="CAY">Caerphilly</option>
<option value="CRF">Cardiff</option>
<option value="CMN">Carmarthenshire</option>
<option value="CGN">Ceredigion</option>
<option value="CWY">Conwy</option>
<option value="DEN">Denbighshire</option>
<option value="FLN">Flintshire</option>
<option value="GWN">Gwynedd</option>
<option value="AGY">Isle of Anglesey</option>
<option value="MTY">Merthyr Tydfil</option>
<option value="MON">Monmouthshire</option>
<option value="NTL">Neath Port Talbot</option>
<option value="NWP">Newport</option>
<option value="PEM">Pembrokeshire</option>
<option value="POW">Powys</option>
<option value="RCT">Rhondda, Cynon, Taff</option>
<option value="SWA">Swansea</option>
<option value="TOF">Torfaen</option>
<option value="VGL">Vale of Glamorgan, The</option>
<option value="WRX">Wrexham</option>

root:c:w:pnlCounty:c:w:pnlIrelandCounty:c:w:cmbCountyState:combobox
<option value="CW">Carlow</option>
<option value="CN">Cavan</option>
<option value="CE">Clare</option>
<option value="C">Cork</option>
<option value="DL">Donegal</option>
<option value="D">Dublin</option>
<option value="G">Galway</option>
<option value="KY">Kerry</option>
<option value="KE">Kildare</option>
<option value="KK">Kilkenny</option>
<option value="LS">Laois</option>
<option value="LM">Leitrim</option>
<option value="L">Limerick</option>
<option value="LD">Longford</option>
<option value="LH">Louth</option>
<option value="MO">Mayo</option>
<option value="MH">Meath</option>
<option value="MN">Monaghan</option>
<option value="OY">Offaly</option>
<option value="RN">Roscommon</option>
<option value="SO">Sligo</option>
<option value="TA">Tipperary</option>
<option value="WH">Westmeath</option>
<option value="WX">Wexford</option>
<option value="WW">Wicklow</option>
<option value="WD">Waterford</option>*/
