/*
Nationality

root:c:w:cmbNationality:v
<option value="AF">Afghani</option>
<option value="AX">Ålandic</option>
<option value="AL">Albanian</option>
<option value="DZ">Algerian</option>
<option value="AS">Samoan</option>
<option value="AD">Andorran</option>
<option value="AO">Angolan</option>
<option value="AI">Anguillan</option>
<option value="AQ">Antarctic</option>
<option value="AG">Antiguan</option>
<option value="AR">Argentine</option>
<option value="AM">Armenian</option>
<option value="AW">Arubian</option>
<option value="AU">Australian</option>
<option value="AT">Austrian</option>
<option value="AZ">Azerbaijani</option>
<option value="BS">Bahameese</option>
<option value="BH">Bahrainian</option>
<option value="BD">Bangladeshi</option>
<option value="BB">Barbadian</option>
<option value="BY">Belarusian</option>
<option value="BE">Belgian</option>
<option value="BZ">Belizean</option>
<option value="BJ">Beninese</option>
<option value="BM">Bermudan</option>
<option value="BT">Bhutanese</option>
<option value="BO">Bolivian</option>
<option value="BA">Bosnian</option>
<option value="BW">Motswana</option>
<option value="BV">Bouvet Island</option>
<option value="BR">Brazilian</option>
<option value="IO">British Indian Ocean Territory</option>
<option value="VG">Virgin Islander</option>
<option value="BN">Bruneian</option>
<option value="BG">Bulgarian</option>
<option value="BF">Burkinabe</option>
<option value="MM">Myanmarese</option>
<option value="BI">Burundian</option>
<option value="KH">Cambodian</option>
<option value="CM">Cameroonian</option>
<option value="CA">Canadian</option>
<option value="CV">Cape Verdean</option>
<option value="BQ">Caribbean Netherlands</option>
<option value="KY">Caymanian</option>
<option value="CF">Central African</option>
<option value="TD">Chadian</option>
<option value="CL">Chilean</option>
<option value="CN">Chinese</option>
<option value="CX">Christmas Islander</option>
<option value="CC">Cocossian</option>
<option value="CO">Colombian</option>
<option value="KM">Comoran</option>
<option value="CG">Congolese</option>
<option value="CK">Cook Islander</option>
<option value="CR">Costa Rican</option>
<option value="CI">Ivorian</option>
<option value="HR">Croatian</option>
<option value="CU">Cuban</option>
<option value="CW">Curaçaoan</option>
<option value="CY">Cypriot</option>
<option value="CZ">Czech</option>
<option value="CD">Congolese</option>
<option value="DK">Danish</option>
<option value="DJ">Djiboutian</option>
<option value="DM">Dominican</option>
<option value="DO">Dominican Republic</option>
<option value="EC">Ecuadorean</option>
<option value="EG">Egyptian</option>
<option value="SV">Salvadorean</option>
<option value="GQ">Equatorial Guinean</option>
<option value="ER">Eritrean</option>
<option value="EE">Estonian</option>
<option value="ET">Ethiopian</option>
<option value="FK">Falkland Islander</option>
<option value="FO">Faroese</option>
<option value="FJ">Fijian</option>
<option value="FI">Finnish</option>
<option value="FR">French</option>
<option value="GF">French Guianese</option>
<option value="PF">French Polynesian</option>
<option value="TF">French Southern Territories</option>
<option value="GA">Gabonese</option>
<option value="GM">Gambian</option>
<option value="GE">Georgian</option>
<option value="DE">German</option>
<option value="GH">Ghanaian</option>
<option value="GI">Gibralterian</option>
<option value="GR">Greek</option>
<option value="GL">Greenlander</option>
<option value="GD">Grenadian</option>
<option value="GP">Guadeloupean</option>
<option value="GU">Guamanian</option>
<option value="GT">Guatemalan</option>
<option value="GG">Guernsey</option>
<option value="GN">Guinean</option>
<option value="GW">Guinean</option>
<option value="GY">Guyanese</option>
<option value="HT">Haitian</option>
<option value="HM">Heard and McDonald Islands</option>
<option value="HN">Honduran</option>
<option value="HK">Hong Konger</option>
<option value="HU">Hungarian</option>
<option value="IS">Icelander</option>
<option value="IN">Indian</option>
<option value="ID">Indonesian</option>
<option value="IR">Iranian</option>
<option value="IQ">Iraqi</option>
<option value="IE">Irish</option>
<option value="IM">Manx</option>
<option value="IL">Israeli</option>
<option value="IT">Italian</option>
<option value="JM">Jamaican</option>
<option value="JP">Japanese</option>
<option value="JE">Jersey</option>
<option value="JO">Jordanian</option>
<option value="KZ">Kazakhstani</option>
<option value="KE">Kenyan</option>
<option value="KI">I-Kiribati</option>
<option value="KW">Kuwaiti</option>
<option value="KG">Kyrgyzstani</option>
<option value="LA">Laotian</option>
<option value="LV">Latvian</option>
<option value="LB">Lebanese</option>
<option value="LS">Mosotho</option>
<option value="LR">Liberian</option>
<option value="LY">Libyan</option>
<option value="LI">Liechtensteiner</option>
<option value="LT">Lithunian</option>
<option value="LU">Luxembourger</option>
<option value="MO">Macanese</option>
<option value="MK">Macedonian</option>
<option value="MG">Malagasy</option>
<option value="MW">Malawian</option>
<option value="MY">Malaysian</option>
<option value="MV">Maldivan</option>
<option value="ML">Malian</option>
<option value="MT">Maltese</option>
<option value="MH">Marshallese</option>
<option value="MQ">Martinican</option>
<option value="MR">Mauritanian</option>
<option value="MU">Mauritian</option>
<option value="YT">Mahoran</option>
<option value="MX">Mexican</option>
<option value="FM">Micronesian</option>
<option value="MD">Moldovan</option>
<option value="MC">Monacan</option>
<option value="MN">Mongolian</option>
<option value="ME">Montenegrin</option>
<option value="MS">Montserratian</option>
<option value="MA">Moroccan</option>
<option value="MZ">Mozambican</option>
<option value="NA">Namibian</option>
<option value="NR">Nauruan</option>
<option value="NP">Nepalese</option>
<option value="NL">Dutch</option>
<option value="NC">New Caledonian</option>
<option value="NZ">New Zealander</option>
<option value="NI">Nicaraguan</option>
<option value="NE">Nigerien</option>
<option value="NG">Nigerian</option>
<option value="NU">Niuean</option>
<option value="NF">Norfolk Islander</option>
<option value="KP">North Korean</option>
<option value="MP">Northern Mariana Islander</option>
<option value="NO">Norwegian</option>
<option value="OM">Omani</option>
<option value="PK">Pakistani</option>
<option value="PW">Palauan</option>
<option value="PS">Palestinian</option>
<option value="PA">Panamanian</option>
<option value="PG">Papua New Guinean</option>
<option value="PY">Paraguayan</option>
<option value="PE">Peruvian</option>
<option value="PH">Filipino</option>
<option value="PN">Pitcairn Islander</option>
<option value="PL">Polish</option>
<option value="PT">Portuguese</option>
<option value="PR">Puerto Rican</option>
<option value="QA">Qatari</option>
<option value="RE">Réunion</option>
<option value="RO">Romanian</option>
<option value="RU">Russian</option>
<option value="RW">Rwandan</option>
<option value="BL">Barthélemois</option>
<option value="SH">Saint Helenian</option>
<option value="KN">Kittian</option>
<option value="LC">Saint Lucian</option>
<option value="MF">Saint Martin (France)</option>
<option value="SX">Saint Martin (Netherlands)</option>
<option value="VC">Saint Vincentian</option>
<option value="WS">Samoan</option>
<option value="SM">Sanmarinese</option>
<option value="ST">São Tomean</option>
<option value="SA">Saudi Arabian</option>
<option value="SN">Senegalese</option>
<option value="RS">Serbian</option>
<option value="SC">Seychellois</option>
<option value="SL">Sierra Leonean</option>
<option value="SG">Singaporean</option>
<option value="SK">Slovakian</option>
<option value="SI">Slovenian</option>
<option value="SB">Solomon Islander</option>
<option value="SO">Somali</option>
<option value="ZA">South African</option>
<option value="GS">South Georgia and the South Sandwich Islands</option>
<option value="KR">South Korean</option>
<option value="SS">Sudanese</option>
<option value="ES">Spanish</option>
<option value="LK">Sri Lankan</option>
<option value="PM">Saint-Pierrais</option>
<option value="SD">Sudanese</option>
<option value="SR">Surinamer</option>
<option value="SJ">Svalbard and Jan Mayen Islands</option>
<option value="SZ">Swazi</option>
<option value="SE">Swedish</option>
<option value="CH">Swiss</option>
<option value="SY">Syrian</option>
<option value="TW">Taiwanese</option>
<option value="TJ">Tajikistani</option>
<option value="TZ">Tanzanian</option>
<option value="TH">Thai</option>
<option value="TL">Timorese</option>
<option value="TG">Togolese</option>
<option value="TK">Tokelauan</option>
<option value="TO">Tongan</option>
<option value="TT">Trinidadian</option>
<option value="TN">Tunisian</option>
<option value="TR">Turkish</option>
<option value="TM">Turkmen</option>
<option value="TC">Turks and Caicos Islander</option>
<option value="TV">Tuvaluan</option>
<option value="UG">Ugandan</option>
<option value="UA">Ukrainian</option>
<option value="AE">Emirian</option>
<option value="GB">British</option>
<option value="UM">United States Minor Outlying Islands</option>
<option value="US">American</option>
<option value="VI">Virgin Islander</option>
<option value="UY">Uruguayan</option>
<option value="UZ">Uzbekistani</option>
<option value="VU">Ni-Vanuatu</option>
<option value="VA">Vatican</option>
<option value="VE">Venezuelan</option>
<option value="VN">Vietnamese</option>
<option value="WF">Wallisian</option>
<option value="EH">Western Saharan</option>
<option value="YE">Yemeni</option>
<option value="ZM">Zambian</option>
<option value="ZW">Zimbabwean</option>*/
