package com.r2development.leveris.qa.utils.datamodelvalidator.borrowerloanapp;

public interface IBWInterface {

    /**
     * For the inner working of the DataModel Project
     */
    String
            borrower = "Borrower",
            coapplicant = "Coapplicant",
            quotation = "Quotation",
            packagePath = "DataModelValidator.borrowerLoanApp.",
            coappEmploymentAndIncomePath = packagePath + "CoapplicantEmploymentAndIncome.",
            borrowerEmploymentAndIncomePath = packagePath + "EmploymentAndIncome.",
            personalDetailsPath = packagePath + "PersonalDetails.",
            quotationPath = packagePath + quotation + ".",
            registrationPath = packagePath + "Registration.",
            yourAccountsPath = packagePath + "YourAccounts.",
            yourDependentsPath = packagePath + "YourDependents.",
            yourFinancialAssetsPath = packagePath + "YourFinancialAssets.",
            yourFinancialCommitmentsPath = packagePath + "YourFinancialCommitments.",
            yourFundingPath = packagePath + "YourFunding",
            yourPropertiesPath = packagePath + "YourProperties.";

    /**
     * Label reflections between Excel and validator to Application field labels
     */
    String  personalDetailsNationality = "Nationality",
            personalDetailsSubNationalityIrishValue = "Irish",
            personalDetailsHowManyYears = "How many years have you been resident in the Republic of Ireland?",
            personalDetailsCountry = "Country",

            thisAccommodationIsRentedOnContractValue = "Rented on contract",
            thisAccommodationIsRentedFromFamilyFriendsValue = "Rented from family/friends",
            thisAccommodationIsOtherValue = "Other",
            thisAccommodationIs = "This accommodation is",

            addAnotherMortgageAccount = "ADD ANOTHER MORTGAGE ACCOUNT",
            addAnotherMortgageAccountYesValue = "Yes",

            dateOfBirth = "Date of birth",
            maritalStatus = "Marital Status",
            amount = "Amount",
            currently = "Currently",
            currentlyYesValue = "Yes",
            countryIreland = "Ireland",
            countyState = "County/State",
            county = "County",
            description = "Description",
            endDate = "End date",
            startDate = "Start date",
            rent = "Rent",
            haveYouLivedHereFor3Years = "Have You lived on this address for the last 3 years?",
            haveYouLivedHereFor3YearsNoValue = "No",
            previousCountry = "Country",
            firstName = "First name",
            mortgageType = "Mortgage Type",
            firstBorrowerAge = "First Borrower Age",
            borrowersMaritalStatus = "Borrowers " + maritalStatus,
            lastName = "Last name",
            emailAddress = "Email address",
            phoneNumber = "Phone number",
            createPassword = "Create password",
            gender = "Gender",
            genderFemaleValue = "Female",
            maidenName = "Maiden name",
            addressLine1 = "Address line 1",
            addressLine2 = "Address line 2",
            townCity = "Town/City",
            postCodeZip = "Postcode/ZIP (optional)",
            postCode = "Post code",
            single = "single",
            mortgageProvider = "Mortgage provider",
            mortgageAccountNumber = "Mortgage account number",
            currentBalance = "Current balance",
            monthlyPayment = "Monthly payment",
            interestOnly = "Interest only",
            currentInterestRate = "Current interest rate",
            rateType = "Rate type",
            grossSalary = "Gross salary",
            regularOvertime = "Regular overtime",
            sourceOfAdditionalIncome = "Source of additional income",
            timeEarningThisIncome = "Time earning this income",
            grossIncome = "Gross income",
            regularGuaranteedBonus = "Regular guaranteed bonus",
            guaranteedCommission = "Guaranteed commission",
            occupation = "Occupation",
            employersName = "Employer's name",
            businessName = "Business name",
            netProfitLastYear = "Net profit last year",
            netProfitPreviousYear = "Net profit previous year",
            accountantNamePractice = "Accountant name/practice",
            natureOfBusiness = "Nature of business",
            natureOfOtherFinancialAsset = "Nature of other financial asset",

            countryProperties = personalDetailsCountry,
            countryPropertiesIrelandValue = countryIreland,
            countyProperties = county,

            employmentType = "Employment Type",
            employmentTypePermanentValue = "Permanent",
            employmentTypeContractValue = "Contract",
            employmentTypeTemporaryValue = "Temporary",
            employmentAndIncomeCategory = "Category",

            employmentAndIncomeCategoryPAYEValue = "PAYE",
            employmentAndIncomeCategoryUnemployedHomemakerValue = "UnemployedHomemaker",
            employmentAndIncomeCategoryOtherValue = "Other",
            employmentAndIncomeCategorySelfEmployedValue = "Self Employed",
            employmentAndIncomeCategoryCivilServantValue = "Civil Servant",

            secondBorrowerAge = "Second Borrower Age",

            incomeTypeFirstBorrower = "Income Type First Borrower",
            incomeTypeSecondBorrower = "Income Type Second Borrower",
            incomeAmountFirstBorrower = "Income Amount First Borrower",
            incomeAmountSecondBorrower = "Income Amount Second Borrower",
            isThisPropertyMortgaged = "Is this property mortgaged?",
            isThisPropertyMortgagedYesValue = "Yes",
            itThisPropertyMortgagedNoMortgageRepaid = "No, Mortgage Repaid",
            isThisPropertyMortgagedNoNeverHadAMortgage = "No, Never Had a Mortgage",
            isTheMortgageNowOrItHasBeenIn = "Is the mortgage now or has it been in …",
            yourPropertiesDoYouPlanToSellIt = "Do you plan to sell it …",
            yourPropertiesEstimatedValueSaleAgreedPrice = "Estimated value/sale agreed price",
            yourPropertiesYearRepaid = "Year repaid",
            otherFinancialCommitments = "Other Financial Commitments",

            pleaseOutlineAnyShortTermDebt = "Please outline any short-term debt…",
            pleaseOutlineAnyShortTermDebtYesValue = "Yes",
            financialCommitmentsWhatIsTypeOfFinancialCommitment = "What is type of financial commitment?",
            financialCommitmentsWhatIsTypeOfFinancialCommitmentCreditCardValue = "Credit Card",
            financialCommitmentsWhatIsTypeOfFinancialCommitmentCarLoanValue = "Car Loan",
            financialCommitmentsWhatIsTypeOfFinancialCommitmentMaintenancePaymentValue = "Maintenance Payment",
            financialCommitmentsWhatIsTypeOfFinancialCommitmentOtherValue = "Other",
            financialCommitmentsWhatIsTypeOfFinancialCommitmentStudentLoanValue = "Student Loan",
            financialCommitmentsWhatIsTypeOfFinancialCommitmentPersonalLoanValue = "Personal Loan",
            financialCommitmentsMonthlyMaintenancePayment = "Monthly maintenance payment",

            financialCommitmentsCreditCardProvider = "Credit card provider",
            financialCommitmentsCreditCardType = "Credit card type",
            financialCommitmentsCreditCardLimit = "Credit card limit",
            financialCommitmentsCreditCardBalance = "Credit card balance",
            financialCommitmentsRepaymentAmount = "Repayment amount",
            financialCommitmentOtherValue = "Other value",
            financialCommitmentsOutstandingAmountBalance = "Outstanding amount (balance)",
            financialCommitmentsFinancialInstitution = "Financial institution",
            financialCommitmentsRepaymentFrequency = "Repayment frequency",
            financialCommitmentsFinalRepaymentDate = "Final repayment date",
            financialCommitmentsPurposeOfTheLoan = "Purpose of the loan",

            doYouHaveAnyAssets = "Do You have any assets like shares, or land?",
            doYouHaveAnyAssetsYesValue = "Yes",

            numberOfBorrowers = "Number of Borrowers",
            numberOfBorrowersTwoBorrowersValue = "two borrowers",
            numberOfDependents = "Number of Dependents",

            whatIsTypeOfAssetInvestmentProductFundsBonds = "Investment Product FundsBonds",

            yourAccountsWhatIsTheSourceOfFunds = "What is the source of funds?",
            YourAccountsWhatIsTheSourceOfFundsSavingsAccountValue = "Savings Account",
            YourAccountsWhatIsTheSourceOfFundsCurrentAccountValue = "Current Account",
            yourAccountsWhatIsTheSourceOfFundsGiftValue = "Gift",
            yourAccountsWhatIsTheSourceOfFundsInheritanceValue= "Inheritance",
            yourAccountsWhatIsTheSourceOfFundsOtherValue = "Other",
            yourAccountsStatementDateOptional = "Statement Date (optional)",
            yourAccountsAddAnAccount = "Add an account",
            yourAccountsAddAnAccountValueOther = "Other",
            yourAccountsAddAccountManually = "Add Account manually",

            selectBorrowerToWhomThisApplies = "Select borrower to whom this applies",
            yourAccountsAccountProvider = "Account provider",
            yourAccountsLastFourDigitsOfAccountNumberIBAN = "Last four digits of account number/iban?",
            yourAccountSourceOfSavings = "Source of savings",
            yourAccountsAccountBalance = "Account balance",
            yourAccountsOverdraftLimit = "Overdraft limit",
            whatIsTypeOfAsset = "What is type of asset?",
            whatIsTypeOfAssetLifePolicyValue = "Life Policy",
            whatIsTypeOfAssetLandSiteValue = "LandSite",
            whatIsTypeOfAssetOtherValue = "Other",
            whatIsTypeOfAssetSharesValue = "Shares",
            whatIsTypeOfAssetShareOptionsValue = "Share Options",
            yourAssetsLifePolicyCompany = "Life policy company",
            yourAssetsCurrentEncashmentValue = "Current encashment value",
            yourAssetsCompanyInWhichSharesHeld = "Company in which shares held",
            yourAssetsShareOptionsExerciseDate = "Share options exercise date",
            yourAssetsCurrentValueOfShareOptions = "Current value of share options",
            yourAssetsCurrentValueOfShares = "Current value of shares",
            yourAssetsCurrentValue = "Current value",
            yourAssetsMaturityDate = "Maturity Date",

            yourDependentsValue = "Your Dependents",
            yourDependentsDateOfBirth = dateOfBirth,
            yourDependentsDoEitherOfYouHaveAnyOtherDependents = "Do either of You have any other Dependents?",
            YourDependentsDoEitherOfYouHaveAnyOtherDependentsYesValue = "Yes",

            previousAddressLine1 = addressLine1,
            previousAddressLine2 = addressLine2,
            previousTownCity = townCity,
            previousPostCodeZip = postCodeZip,

            doEitherOfYouHaveAStakeInAnyProperty = "Do either of you have a stake in any property?",
            doEitherOfYouHaveAStakeInAnyPropertyYesValue = "Yes",
            yourPropertiesPropertyCategory = "Property Category",
            yourPropertiesPropertyCategoryPrincipalDwellingHouseValue = "Principal Dwelling House",
            yourPropertiesPropertyCategoryInvestmentValue = "Investment",
            yourPropertiesPropertyCategoryHolidayHomeValue = "Holiday Home",
            yourPropertiesMonthlyRent = "Monthly rent",
            yourPropertiesRentIs = "Rent is",
            yourPropertiesPropertyType = "Property type",
            yourPropertiesNumberOfBedrooms = "Number of bedrooms",
            yourPropertiesYearPropertyWasAcquired = "Year property was acquired",
            yourPropertiesOriginalPurchasePrice = "Original purchase price",

            borrowerString = "Bw",
            coapplicantString = "Coapp",
            yourFinancialCommitments = "Your Financial Commitments",
            yourFunding = "Your Funding",
            yourProperties = "Your Properties",
            yourAccounts = "Your Accounts",
            yourFinancialAssets = "Your Financial Assets",
            employmentAndIncome = "Employment and Income",
            personalDetails = "Personal Details",
            inviteCoapplicant = "Invite Coapplicant",
            registration = "Borrower Test Data",

            /**
             * Excel Sheet Names Strings
             */
            yourDependents =                                IBWInterface.yourDependentsValue,
            yourPropertiesInvestment =                      IBWInterface.yourProperties + " - " + IBWInterface.yourPropertiesPropertyCategoryInvestmentValue,
            yourPropertiesHolidayHome =                     IBWInterface.yourProperties + " - " + IBWInterface.yourPropertiesPropertyCategoryHolidayHomeValue,
            yourPropertiesPrincipalDwellingHouse =          IBWInterface.yourProperties + " - " + IBWInterface.yourPropertiesPropertyCategoryPrincipalDwellingHouseValue,
            yourAccountsCurrentAccount =                    IBWInterface.yourAccounts + " - " + IBWInterface.YourAccountsWhatIsTheSourceOfFundsCurrentAccountValue,
            yourAccountsSavingsAccount =                    IBWInterface.yourAccounts + " - " + IBWInterface.YourAccountsWhatIsTheSourceOfFundsSavingsAccountValue,
            yourFinancialAssetsOther =                      IBWInterface.yourFinancialAssets + " - " + IBWInterface.whatIsTypeOfAssetOtherValue,
            yourFinancialAssetsLifePolicy =                 IBWInterface.yourFinancialAssets + " - " + IBWInterface.whatIsTypeOfAssetLifePolicyValue,
            yourFinancialAssetsLandSite =                   IBWInterface.yourFinancialAssets + " - " + IBWInterface.whatIsTypeOfAssetLandSiteValue,
            yourFinancialAssetsShareOptions =               IBWInterface.yourFinancialAssets + " - " + IBWInterface.whatIsTypeOfAssetShareOptionsValue,
            yourFinancialAssetsShares =                     IBWInterface.yourFinancialAssets + " - " + IBWInterface.whatIsTypeOfAssetSharesValue,
            yourFinancialAssetsInvestmentProductFundsBonds = IBWInterface.yourFinancialAssets + " - " + IBWInterface.whatIsTypeOfAssetInvestmentProductFundsBonds,

            yourFundingGift =                               IBWInterface.yourFunding + " - " + IBWInterface.yourAccountsWhatIsTheSourceOfFundsGiftValue,
            yourFundingInheritance =                        IBWInterface.yourFunding + " - " + IBWInterface.yourAccountsWhatIsTheSourceOfFundsInheritanceValue,
            yourFundingOther =                              IBWInterface.yourFunding + " - " + IBWInterface.yourAccountsWhatIsTheSourceOfFundsOtherValue,

            yourFinancialCommitmentsCarLoan =               IBWInterface.yourFinancialCommitments + " - " + IBWInterface.financialCommitmentsWhatIsTypeOfFinancialCommitmentCarLoanValue,
            yourFinancialCommitmentsCreditCard =            IBWInterface.yourFinancialCommitments + " - " + IBWInterface.financialCommitmentsWhatIsTypeOfFinancialCommitmentCreditCardValue,
            yourFinancialCommitmentsMaintenancePayment =    IBWInterface.yourFinancialCommitments + " - " + IBWInterface.financialCommitmentsWhatIsTypeOfFinancialCommitmentMaintenancePaymentValue,
            yourFinancialCommitmentsOther =                 IBWInterface.yourFinancialCommitments + " - " + IBWInterface.financialCommitmentsWhatIsTypeOfFinancialCommitmentOtherValue,
            yourFinancialCommitmentsPersonalLoan =          IBWInterface.yourFinancialCommitments + " - " + IBWInterface.financialCommitmentsWhatIsTypeOfFinancialCommitmentPersonalLoanValue,
            yourFinancialCommitmentsStudentLoan =           IBWInterface.yourFinancialCommitments + " - " + IBWInterface.financialCommitmentsWhatIsTypeOfFinancialCommitmentStudentLoanValue,

            coappEmploymentAndIncomeUnemployedHomemaker =   IBWInterface.coapplicantString + " - " + IBWInterface.employmentAndIncome + " - " + IBWInterface.employmentAndIncomeCategoryUnemployedHomemakerValue,
            coappEmploymentAndIncomeCivilServant =          IBWInterface.coapplicantString + " - " + IBWInterface.employmentAndIncome + " - " + IBWInterface.employmentAndIncomeCategoryCivilServantValue,
            coappEmploymentAndIncomeOther =                 IBWInterface.coapplicantString + " - " + IBWInterface.employmentAndIncome + " - " + IBWInterface.employmentAndIncomeCategoryOtherValue,
            coappEmploymentAndIncomeSelfEmployed =          IBWInterface.coapplicantString + " - " + IBWInterface.employmentAndIncome + " - " + IBWInterface.employmentAndIncomeCategorySelfEmployedValue,
            coappEmploymentAndIncomePAYE =                  IBWInterface.coapplicantString + " - " + IBWInterface.employmentAndIncome + " - " + IBWInterface.employmentAndIncomeCategoryPAYEValue,
            borrowerEmploymentAndIncomeUnemployedHomemaker = IBWInterface.borrowerString + " - " + IBWInterface.employmentAndIncome + " - " + IBWInterface.employmentAndIncomeCategoryUnemployedHomemakerValue,
            borrowerEmploymentAndIncomeCivilServant =       IBWInterface.borrowerString + " - " + IBWInterface.employmentAndIncome + " - " + IBWInterface.employmentAndIncomeCategoryCivilServantValue,
            borrowerEmploymentAndIncomeOther =              IBWInterface.borrowerString + " - " + IBWInterface.employmentAndIncome + " - " + IBWInterface.employmentAndIncomeCategoryOtherValue,
            borrowerEmploymentAndIncomeSelfEmployed =       IBWInterface.borrowerString + " - " + IBWInterface.employmentAndIncome + " - " + IBWInterface.employmentAndIncomeCategorySelfEmployedValue,
            borrowerEmploymentAndIncomePAYE =               IBWInterface.borrowerString + " - " + IBWInterface.employmentAndIncome + " - " + IBWInterface.employmentAndIncomeCategoryPAYEValue,
            borrowerPersonalDetails =                       IBWInterface.borrowerString + " - " + IBWInterface.personalDetails,
            coapplicantPersonalDetails =                    IBWInterface.coapplicantString + " - " + IBWInterface.personalDetails;

}
